#!/bin/sh
CONFIG_FILE=/etc/burrow/burrow.toml
KAFKA_VERSION=${KAFKA_VERSION:-0.10.1.0}

sed -i "s~{ZOOKEEPER_SERVERS}~${ZOOKEEPER_SERVERS}~" $CONFIG_FILE
sed -i "s~{ZOOKEEPER_PATH}~${ZOOKEEPER_PATH}~" $CONFIG_FILE
sed -i "s~{KAFKA_BROKERS}~${KAFKA_BROKERS}~" $CONFIG_FILE
sed -i "s~{KAFKA_VERSION}~${KAFKA_VERSION}~" $CONFIG_FILE
sed -i "s~{BURROW_KAFKA_USERNAME}~${BURROW_KAFKA_USERNAME}~" $CONFIG_FILE
sed -i "s~{BURROW_KAFKA_PASSWORD}~${BURROW_KAFKA_PASSWORD}~" $CONFIG_FILE
sed -i "s~{SHA_ALGORITHM}~${SHA_ALGORITHM}~" $CONFIG_FILE

echo "start"
cat $CONFIG_FILE

exec /etc/burrow/burrow -config-dir /etc/burrow "${@}"