[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"

[logging]
filename="logs/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[{ZOOKEEPER_SERVERS}]
timeout=6
root-path="/burrow"

[client-profile.burrow-kafka-profile]
kafka-version={KAFKA_VERSION}
client-id="burrow-test"
sasl="burrow-kafka-profile"

[sasl.burrow-kafka-profile]
username={BURROW_KAFKA_USERNAME}
password={BURROW_KAFKA_PASSWORD}
handshake-first=false
algorithm={SHA_ALGORITHM}

[cluster.local]
class-name="kafka"
servers=[{KAFKA_BROKERS}]
client-profile="burrow-kafka-profile"

topic-refresh=120
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[{KAFKA_BROKERS}]
client-profile="burrow-kafka-profile"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[consumer.local_zk]
class-name="kafka_zk"
cluster="local"
servers=[{ZOOKEEPER_SERVERS}]
zookeeper-path={ZOOKEEPER_PATH}
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[httpserver.default]
address=":8005"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1
